### PR TITLE
Added ability to handle tests & suite setup that return promises.

### PR DESCRIPTION
**Pull request by christav**
You're probably not going to like this one. 😄 

With this change, if a suite or test function returns a promise,
joe will then wait for that promise to complete before continuing
without requiring that you take a completion callback or call it.

This simplifies testing with promise-based APIs and also lets you
use async/await inside test function and suite setup.

For example, this would now work:
```
joe.test('do some database stuff', function () {
  return getSomeStuffFromDb()
    .then((stuff) => {
        expect(stuff).to.exist
    })
})
```
or even:
```
joe.test('do some database stuff', async function () {
  const stuff = await getSomeStuffFromDb()
  expect(stuff).to.exist
})
```

I have run the existing test suite and everything still passes, and I've written
tests of the new functionality standalone, but I'm not sure how to hook
it into the official test suite (seems like changes are needed across multiple
repos?) Some pointers on how best to add those tests would be very helpful.

Hope this is useful/reasonable, it's something our projects in mocha use
all the time and I'd love to have it here as well.

### CODE REVIEW

**Comment by balupton** [comment]
This is great. I've been thinking about promise integration for a while, and have been considering it at the taskgroup layer. Will merge this in on the next pull request day - I've made it the first monday of every month, so will be the 6th of November.

**Comment by christav** [comment]
Cool, thanks!

Any suggestions/guidance on adding tests for the feature? I'm not sure how the infrastructure works there.

**Comment by balupton** [comment]
Sorry for the delay on this. Had several hiccups with my dev environment recently. Will get to it next week.

**Comment by christav** [comment]
No problem, the PR's not going anywhere in the meantime. 😃

**Comment by christav** [comment]
@balupton So is anything going to happen with this?

**Comment by balupton** [comment]
@christav so sorry Chris, just haven't found the time, which is unacceptable.

Let me spend the day setting things up so to do releases, all I need to do is add people like you to the Code Team (giving you push access).

Sorry!

Will be on the Bevry slack today, so we can chat there to resolve this. Otherwise hit me up on Wire.com - username `balupton`

**Comment by balupton** [comment]
@christav you should have got an invite to join a bevry team to give you write access to this repo

once you have merged to master, and bumped the package.json version, and added a changelog entry, committed the changes, run `npm run our:release` to tag and push - travis will release to npm if all went well

**Comment by christav** [comment]
@balupton Thanks for the invite. I've accepted it and will probably finish this up this weekend.

**Comment by balupton** [comment]
Can we add this functionality directly to TaskGroup instead of Joe?

**Comment by christav** [comment]
I took a quick look at it, and I'm not sure. My original thought was to somehow wrap a promise in a Task. However, Tasks expose a lot of internal information about the state of a Task that isn't available for promises. I'm not sure what the proper mapping would be in those cases.

In any event there would still need to be some code over here to detect that a promise has been returned and do the right thing.

**Comment by balupton** [comment]
I'm working on TypeScript rewrites of all these projects currently. Will see if promise support can be added or not to TaskGroup or Ambi directly.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by christav** [comment]
I've realized there's a better way to implement this, and with the other stuff mentioned for the project I'm going to close this for the moment. If you'd like help on the Typescript rewrite/rework let me know, I'd love to help.

**Comment by balupton** [comment]
/ref https://github.com/bevry/ambi/issues/2#issuecomment-443487854

**Comment by balupton** [comment]
@christav can you add me on wire.com - my username is `balupton` - and we can collaborate on the typescript conversions

**Pull request closed without merging**
